language: java
jdk:
  - openjdk11

script:
  - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - nicobugliot@gmail.com
    on_failure: always